version: "3"

services:
  api:
    container_name: ck_kis_companies_api
    build: .
    command: gunicorn --bind=0.0.0.0:8000 api.__main__:__hug_wsgi__
    # expose:
    #   - "8001"

  nginx:
    container_name: ck_kis_companies_nginx
    depends_on:
      - api
    image: nginx:latest
    ports:
      - "8011:80"
    volumes:
      - .:/app
      - ./config/nginx:/etc/nginx/conf.d

networks:
  default:
    name: kis_network